#! /usr/bin/env python

import subprocess
import os
import redspot_notebooks

dir_path = os.path.dirname(os.path.realpath(redspot_notebooks.__file__))

subprocess.run(["jupyter", "notebook", "--notebook-dir", dir_path])
